name: Run with Maven Pipeline

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  build_and_verify:
    if: false # Prevents this job from running
    name: Run GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 15  # <--- Cancels the entire job if it takes longer than 15 minutes
    permissions:
      contents: read # Required for actions/checkout
      issues: write # Any other permissions you need
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java (v26)
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -B clean verify --no-transfer-progress

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
