name: Run with Maven

on:
  pull_request:
    types: [opened, syncronize, reopened]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  build_and_verify:
    name: Run Merge Checks
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repro
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          architecture: x86
          cache: 'maven'
      
      - name: Build with Maven
        run: ./mvnw -B clean verify --no-transfer-progress

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results

      
